let's try to improve Dockerfile

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,25 +6,37 @@ services:
 
 variables:
   DOCKER_DRIVER: overlay2
-  IMAGE_TAG: $CI_REGISTRY_IMAGE/maven-jdk-21:latest
+  BASE_IMAGE_TAG: $CI_REGISTRY_IMAGE/base-maven-jdk-21:latest
+  APP_IMAGE_TAG: $CI_REGISTRY_IMAGE/my-app:latest
 
 stages:
+  - build_base_image
   - build_image
   - test
   - deploy
 
+build_base_image:
+  stage: build_base_image
+  script:
+    - echo "Checking if the base Docker image already exists..."
+    - if docker pull "$BASE_IMAGE_TAG"; then
+      echo "Base image found in registry. Skipping build...";
+      else
+      echo "Base image not found. Building the base Docker image...";
+      docker build -f Dockerfile.base -t "$BASE_IMAGE_TAG" .
+      echo "Pushing the base image to the registry...";
+      docker push "$BASE_IMAGE_TAG";
+      fi
+  only:
+    - schedules
+
 build_image:
   stage: build_image
-  before_script:
-    - if [ -z $(docker images -q $IMAGE_TAG) ]; then
-      echo "Logging into GitLab Registry...";
-      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY;
-      fi
   script:
     - echo "Building the Docker image..."
-    - docker build -t "$IMAGE_TAG" .
-    - echo "Pushing the image to the registry..."
-    - docker push "$IMAGE_TAG"
+    - docker build -t "$APP_IMAGE_TAG" .
+    - echo "Pushing the app image to the registry..."
+    - docker push "$APP_IMAGE_TAG"
 
 cache:
   key: "$CI_COMMIT_REF_NAME"
@@ -33,7 +45,7 @@ cache:
 
 test:
   stage: test
-  image: maven:3.9.5-eclipse-temurin-21-alpine
+  image: $BASE_IMAGE_TAG
   script:
     - echo "Running tests..."
     - mvn test
@@ -41,15 +53,12 @@ test:
 deploy:
   stage: deploy
   image: docker:24.0.7
-  before_script:
-    - docker info
   script:
     - echo "Deploying the application..."
-    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
-    - docker pull "$IMAGE_TAG" || true
-    - docker stop elektrihind-app-container || true
-    - docker rm elektrihind-app-container || true
-    - docker run -d -p 8080:8080 --restart always --name elektrihind-app-container -e TELEGRAM_ELEKTRITEEMU_TOKEN="$TELEGRAM_ELEKTRITEEMU_TOKEN" -e TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" -e OMDB_API_KEY="$OMDB_API_KEY" "$IMAGE_TAG"
+    - docker pull "$APP_IMAGE_TAG"
+    - docker stop my-app-container || true
+    - docker rm my-app-container || true
+    - docker run -d -p 8080:8080 --name my-app-container "$APP_IMAGE_TAG"
   only:
     - main
   tags:
